sudo rm -rf $PWD/include/fluids/
sudo rm -rf $PWD/include/utl/
sudo rm -rf $PWD/include/Eigen/
sudo rm -rf $PWD/include/OpenEXR/
sudo rm -rf $PWD/include/Alembic/
sudo rm -rf $PWD/bin/Alembic/
sudo rm -rf $PWD/vfxepoch_libs/libVFXEpoch.a
sudo rm -rf $PWD/build/
sudo rm -rf $PWD/external_libs/ILM/ilmbase-2.2.0
sudo rm -rf $PWD/external_libs/ILM/openexr-2.2.0
sudo rm -rf $PWD/external_libs/SPI/alembic-1.7.3
